// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nuts_Yarden_Irit_Shiran.Server.Data;

namespace Nuts_Yarden_Irit_Shiran.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220829171849_FixClass")]
    partial class FixClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Nuts_Yarden_Irit_Shiran.Shared.Entities.Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Iscorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("newanswer")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Nuts_Yarden_Irit_Shiran.Shared.Entities.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ispublished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Nuts_Yarden_Irit_Shiran.Shared.Entities.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestText")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Nuts_Yarden_Irit_Shiran.Shared.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nuts_Yarden_Irit_Shiran.Shared.Entities.Answer", b =>
                {
                    b.HasOne("Nuts_Yarden_Irit_Shiran.Shared.Entities.Question", "AnswerQuestion")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerQuestion");
                });

            modelBuilder.Entity("Nuts_Yarden_Irit_Shiran.Shared.Entities.Game", b =>
                {
                    b.HasOne("Nuts_Yarden_Irit_Shiran.Shared.Entities.User", "GameUser")
                        .WithMany("UserGames")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameUser");
                });

            modelBuilder.Entity("Nuts_Yarden_Irit_Shiran.Shared.Entities.Question", b =>
                {
                    b.HasOne("Nuts_Yarden_Irit_Shiran.Shared.Entities.Game", null)
                        .WithMany("QuestList")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nuts_Yarden_Irit_Shiran.Shared.Entities.Game", b =>
                {
                    b.Navigation("QuestList");
                });

            modelBuilder.Entity("Nuts_Yarden_Irit_Shiran.Shared.Entities.User", b =>
                {
                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
